version: '3.8'

services:

  myaebackend:
    image: merionard/myaebe:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/myaebackend
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_SHOW-SQL: "false"
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SECURITY_JWT_TOKEN_SECRET-KEY: my-secret-key

  db:
    image: postgres:latest
    container_name: myaebackend-postgres
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myaebackend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin


  frontend:
    image: merionard/myaefe:latest
    ports:
      - "80:8081"
